use_frameworks!

target 'YXLOrmDB_Example' do
  pod 'YXLOrmDB', :path => '/Users/yuxueliang/Public/LocalGit/YLODB/YXLOrmDB'

  target 'YXLOrmDB_Tests' do
    inherit! :search_paths

    pod 'FMDB'
  end
end
